### ISSUE TITLE
Configuring watcher with multiple endpoints is not possible

### ISSUE THREAD

**Issue by phaniraj75** [casbin/etcd-watcher#4]
We are trying build Auth module with casbin & etcd adapter, etcd adapter supports configuring multiple etcd endpoints for persistance but etcd-watcher allow only one endpoint to be configured to watch with "/casbin" as a key, I was wondering could this be a configurable parameter while creating watcher via "NewWatcher".. or was there is any specific reason for not doing so?

**Comment by hsluoyz** [comment]
Can you make a PR by adding a new constructor?

**Comment by phaniraj75** [comment]
Sure.. I made the changes will verify and submit PR for the same.
