### ISSUE TITLE
About watcher

### ISSUE THREAD

**Issue by andyyumiao** [casbin/etcd-watcher#7]
Why do you need a watcher? Policy are stored in DB, and different casbin instances not accessing the same database?

**Comment by hsluoyz** [comment]
Closed as not being specific.

**Comment by hsluoyz** [comment]
@andyyumiao sorry that I closed the issue so quickly.

The watcher is for such a scenario: there are multiple enforcers, one enforcer has updated the policy into the DB via API, but we want a way to notify other enforcers to know such a change and load the latest policy from DB to their side. It's for synchronization.

You can always see the docs: https://casbin.org/docs/en/watchers and know why it exists.
