### ISSUE TITLE
when to release new version?

### ISSUE THREAD

**Issue by phamtai97** [casbin/etcd-watcher#8]
Hi @hsluoyz .
I see on your branch master is the latest code, when do you release the new version. Because I need etcd-watcher on branch master.

**Comment by hsluoyz** [comment]
@phamtai97 released v1.0.0: https://github.com/casbin/etcd-watcher/releases/tag/v1.0.0

**Comment by hsluoyz** [comment]
@phamtai97 thanks. Does the README in this repo still work? https://github.com/casbin/etcd-watcher#simple-example

If not, can you also make a PR?

**Comment by phamtai97** [comment]
@hsluoyz The example is true only for v0.0.1, so current v1.0.0 is implemented in another way. But the new version 1.0.0 has [issues](https://github.com/casbin/etcd-watcher/issues/10), I am reviewing to pull request to fix it.
